includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Kendall.yaml
  - backbones/Conv64F.yaml

classifier:
  kwargs: 
    train_type: 'diffkendall'
    test_type: 'kendall'
  name: Kendall

backbone:
  name: Conv64F
  kwargs:
    is_flatten: False
    is_feature: False
    leaky_relu: True
    negative_slope: 0.2
    last_pool: False

# backbone:
#   name: resnet12
#   kwargs:
#     maxpool_last2: False
#     is_flatten: False




