data_root: /mnt/d/@extremely_important_files/class_and_homework/sophomore_second_semester/Machine Learning/project/dataset/tiered_imagenet
image_size: 84
use_memory: False
augment: True
augment_times: 1
augment_times_query: 1
workers: 8 # number of workers for dataloader in all threads
dataloader_num: 1
